#AUTOGENERATED! Do not edit manually
APILIST={'apilist': {'interfaces': [{'methods': [{'httpmethod': 'GET',
                                          'name': 'GetClientVersion',
                                          'parameters': [],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetServerVersion',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'IGCVersion_205790'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetClientVersion',
                                          'parameters': [],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetServerVersion',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'IGCVersion_440'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetClientVersion',
                                          'parameters': [],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetServerVersion',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'IGCVersion_570'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetClientVersion',
                                          'parameters': [],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetServerVersion',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'IGCVersion_583950'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetServerVersion',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'IGCVersion_730'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetBucketizedData',
                                          'parameters': [{'description': 'The '
                                                                         'leaderboard '
                                                                         'name '
                                                                         'to '
                                                                         'fetch '
                                                                         'data '
                                                                         'for.',
                                                          'name': 'leaderboardName',
                                                          'optional': False,
                                                          'type': 'string'}],
                                          'version': 1}],
                             'name': 'IPortal2Leaderboards_620'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetAppList',
                                          'parameters': [],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetAppList',
                                          'parameters': [],
                                          'version': 2},
                                         {'httpmethod': 'GET',
                                          'name': 'GetServersAtAddress',
                                          'parameters': [{'description': 'IP '
                                                                         'or '
                                                                         'IP:queryport '
                                                                         'to '
                                                                         'list',
                                                          'name': 'addr',
                                                          'optional': False,
                                                          'type': 'string'}],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'UpToDateCheck',
                                          'parameters': [{'description': 'AppID '
                                                                         'of '
                                                                         'game',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'The '
                                                                         'installed '
                                                                         'version '
                                                                         'of '
                                                                         'the '
                                                                         'game',
                                                          'name': 'version',
                                                          'optional': False,
                                                          'type': 'uint32'}],
                                          'version': 1}],
                             'name': 'ISteamApps'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetCMList',
                                          'parameters': [{'description': "Client's "
                                                                         'Steam '
                                                                         'cell '
                                                                         'ID',
                                                          'name': 'cellid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Max '
                                                                         'number '
                                                                         'of '
                                                                         'servers '
                                                                         'to '
                                                                         'return',
                                                          'name': 'maxcount',
                                                          'optional': True,
                                                          'type': 'uint32'}],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetCSList',
                                          'parameters': [{'description': "Client's "
                                                                         'Steam '
                                                                         'cell '
                                                                         'ID',
                                                          'name': 'cellid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Max '
                                                                         'number '
                                                                         'of '
                                                                         'servers '
                                                                         'to '
                                                                         'return',
                                                          'name': 'maxcount',
                                                          'optional': True,
                                                          'type': 'uint32'}],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetSteamPipeDomains',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'ISteamDirectory'},
                            {'methods': [{'httpmethod': 'POST',
                                          'name': 'PaymentOutReversalNotification',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'ISteamEnvoy'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetNewsForApp',
                                          'parameters': [{'description': 'AppID '
                                                                         'to '
                                                                         'retrieve '
                                                                         'news '
                                                                         'for',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Maximum '
                                                                         'length '
                                                                         'for '
                                                                         'the '
                                                                         'content '
                                                                         'to '
                                                                         'return, '
                                                                         'if '
                                                                         'this '
                                                                         'is 0 '
                                                                         'the '
                                                                         'full '
                                                                         'content '
                                                                         'is '
                                                                         'returned, '
                                                                         'if '
                                                                         "it's "
                                                                         'less '
                                                                         'then '
                                                                         'a '
                                                                         'blurb '
                                                                         'is '
                                                                         'generated '
                                                                         'to '
                                                                         'fit.',
                                                          'name': 'maxlength',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': 'Retrieve '
                                                                         'posts '
                                                                         'earlier '
                                                                         'than '
                                                                         'this '
                                                                         'date '
                                                                         '(unix '
                                                                         'epoch '
                                                                         'timestamp)',
                                                          'name': 'enddate',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': '# of '
                                                                         'posts '
                                                                         'to '
                                                                         'retrieve '
                                                                         '(default '
                                                                         '20)',
                                                          'name': 'count',
                                                          'optional': True,
                                                          'type': 'uint32'}],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetNewsForApp',
                                          'parameters': [{'description': 'AppID '
                                                                         'to '
                                                                         'retrieve '
                                                                         'news '
                                                                         'for',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Maximum '
                                                                         'length '
                                                                         'for '
                                                                         'the '
                                                                         'content '
                                                                         'to '
                                                                         'return, '
                                                                         'if '
                                                                         'this '
                                                                         'is 0 '
                                                                         'the '
                                                                         'full '
                                                                         'content '
                                                                         'is '
                                                                         'returned, '
                                                                         'if '
                                                                         "it's "
                                                                         'less '
                                                                         'then '
                                                                         'a '
                                                                         'blurb '
                                                                         'is '
                                                                         'generated '
                                                                         'to '
                                                                         'fit.',
                                                          'name': 'maxlength',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': 'Retrieve '
                                                                         'posts '
                                                                         'earlier '
                                                                         'than '
                                                                         'this '
                                                                         'date '
                                                                         '(unix '
                                                                         'epoch '
                                                                         'timestamp)',
                                                          'name': 'enddate',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': '# of '
                                                                         'posts '
                                                                         'to '
                                                                         'retrieve '
                                                                         '(default '
                                                                         '20)',
                                                          'name': 'count',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': 'Comma-seperated '
                                                                         'list '
                                                                         'of '
                                                                         'feed '
                                                                         'names '
                                                                         'to '
                                                                         'return '
                                                                         'news '
                                                                         'for',
                                                          'name': 'feeds',
                                                          'optional': True,
                                                          'type': 'string'}],
                                          'version': 2}],
                             'name': 'ISteamNews'},
                            {'methods': [{'httpmethod': 'POST',
                                          'name': 'GetCollectionDetails',
                                          'parameters': [{'description': 'Number '
                                                                         'of '
                                                                         'collections '
                                                                         'being '
                                                                         'requested',
                                                          'name': 'collectioncount',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'collection '
                                                                         'ids '
                                                                         'to '
                                                                         'get '
                                                                         'the '
                                                                         'details '
                                                                         'for',
                                                          'name': 'publishedfileids[0]',
                                                          'optional': False,
                                                          'type': 'uint64'}],
                                          'version': 1},
                                         {'httpmethod': 'POST',
                                          'name': 'GetPublishedFileDetails',
                                          'parameters': [{'description': 'Number '
                                                                         'of '
                                                                         'items '
                                                                         'being '
                                                                         'requested',
                                                          'name': 'itemcount',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'published '
                                                                         'file '
                                                                         'id '
                                                                         'to '
                                                                         'look '
                                                                         'up',
                                                          'name': 'publishedfileids[0]',
                                                          'optional': False,
                                                          'type': 'uint64'}],
                                          'version': 1}],
                             'name': 'ISteamRemoteStorage'},
                            {'methods': [{'httpmethod': 'POST',
                                          'name': 'AuthenticateUser',
                                          'parameters': [{'description': 'Should '
                                                                         'be '
                                                                         'the '
                                                                         'users '
                                                                         'steamid, '
                                                                         'unencrypted.',
                                                          'name': 'steamid',
                                                          'optional': False,
                                                          'type': 'uint64'},
                                                         {'description': 'Should '
                                                                         'be a '
                                                                         '32 '
                                                                         'byte '
                                                                         'random '
                                                                         'blob '
                                                                         'of '
                                                                         'data, '
                                                                         'which '
                                                                         'is '
                                                                         'then '
                                                                         'encrypted '
                                                                         'with '
                                                                         'RSA '
                                                                         'using '
                                                                         'the '
                                                                         'Steam '
                                                                         "system's "
                                                                         'public '
                                                                         'key.  '
                                                                         'Randomness '
                                                                         'is '
                                                                         'important '
                                                                         'here '
                                                                         'for '
                                                                         'security.',
                                                          'name': 'sessionkey',
                                                          'optional': False,
                                                          'type': 'rawbinary'},
                                                         {'description': 'Should '
                                                                         'be '
                                                                         'the '
                                                                         'users '
                                                                         'hashed '
                                                                         'loginkey, '
                                                                         'AES '
                                                                         'encrypted '
                                                                         'with '
                                                                         'the '
                                                                         'sessionkey.',
                                                          'name': 'encrypted_loginkey',
                                                          'optional': False,
                                                          'type': 'rawbinary'}],
                                          'version': 1}],
                             'name': 'ISteamUserAuth'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetTokenDetails',
                                          'parameters': [{'description': 'OAuth2 '
                                                                         'token '
                                                                         'for '
                                                                         'which '
                                                                         'to '
                                                                         'return '
                                                                         'details',
                                                          'name': 'access_token',
                                                          'optional': False,
                                                          'type': 'string'}],
                                          'version': 1}],
                             'name': 'ISteamUserOAuth'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetGlobalAchievementPercentagesForApp',
                                          'parameters': [{'description': 'GameID '
                                                                         'to '
                                                                         'retrieve '
                                                                         'the '
                                                                         'achievement '
                                                                         'percentages '
                                                                         'for',
                                                          'name': 'gameid',
                                                          'optional': False,
                                                          'type': 'uint64'}],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetGlobalAchievementPercentagesForApp',
                                          'parameters': [{'description': 'GameID '
                                                                         'to '
                                                                         'retrieve '
                                                                         'the '
                                                                         'achievement '
                                                                         'percentages '
                                                                         'for',
                                                          'name': 'gameid',
                                                          'optional': False,
                                                          'type': 'uint64'}],
                                          'version': 2},
                                         {'httpmethod': 'GET',
                                          'name': 'GetGlobalStatsForGame',
                                          'parameters': [{'description': 'AppID '
                                                                         'that '
                                                                         "we're "
                                                                         'getting '
                                                                         'global '
                                                                         'stats '
                                                                         'for',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Number '
                                                                         'of '
                                                                         'stats '
                                                                         'get '
                                                                         'data '
                                                                         'for',
                                                          'name': 'count',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Names '
                                                                         'of '
                                                                         'stat '
                                                                         'to '
                                                                         'get '
                                                                         'data '
                                                                         'for',
                                                          'name': 'name[0]',
                                                          'optional': False,
                                                          'type': 'string'},
                                                         {'description': 'Start '
                                                                         'date '
                                                                         'for '
                                                                         'daily '
                                                                         'totals '
                                                                         '(unix '
                                                                         'epoch '
                                                                         'timestamp)',
                                                          'name': 'startdate',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': 'End '
                                                                         'date '
                                                                         'for '
                                                                         'daily '
                                                                         'totals '
                                                                         '(unix '
                                                                         'epoch '
                                                                         'timestamp)',
                                                          'name': 'enddate',
                                                          'optional': True,
                                                          'type': 'uint32'}],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetNumberOfCurrentPlayers',
                                          'parameters': [{'description': 'AppID '
                                                                         'that '
                                                                         "we're "
                                                                         'getting '
                                                                         'user '
                                                                         'count '
                                                                         'for',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'}],
                                          'version': 1}],
                             'name': 'ISteamUserStats'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetServerInfo',
                                          'parameters': [],
                                          'version': 1},
                                         {'httpmethod': 'GET',
                                          'name': 'GetSupportedAPIList',
                                          'parameters': [{'description': 'access '
                                                                         'key',
                                                          'name': 'key',
                                                          'optional': True,
                                                          'type': 'string'}],
                                          'version': 1}],
                             'name': 'ISteamWebAPIUtil'},
                            {'methods': [{'httpmethod': 'POST',
                                          'name': 'PollStatus',
                                          'parameters': [{'description': 'Steam '
                                                                         'ID '
                                                                         'of '
                                                                         'the '
                                                                         'user',
                                                          'name': 'steamid',
                                                          'optional': False,
                                                          'type': 'string'},
                                                         {'description': 'UMQ '
                                                                         'Session '
                                                                         'ID',
                                                          'name': 'umqid',
                                                          'optional': False,
                                                          'type': 'uint64'},
                                                         {'description': 'Message '
                                                                         'that '
                                                                         'was '
                                                                         'last '
                                                                         'known '
                                                                         'to '
                                                                         'the '
                                                                         'user',
                                                          'name': 'message',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Caller-specific '
                                                                         'poll '
                                                                         'id',
                                                          'name': 'pollid',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': 'Long-poll '
                                                                         'timeout '
                                                                         'in '
                                                                         'seconds',
                                                          'name': 'sectimeout',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': 'How '
                                                                         'many '
                                                                         'seconds '
                                                                         'is '
                                                                         'client '
                                                                         'considering '
                                                                         'itself '
                                                                         'idle, '
                                                                         'e.g. '
                                                                         'screen '
                                                                         'is '
                                                                         'off',
                                                          'name': 'secidletime',
                                                          'optional': True,
                                                          'type': 'uint32'},
                                                         {'description': 'Boolean, '
                                                                         '0 '
                                                                         '(default): '
                                                                         'return '
                                                                         'steamid_from '
                                                                         'in '
                                                                         'output, '
                                                                         '1: '
                                                                         'return '
                                                                         'accountid_from',
                                                          'name': 'use_accountids',
                                                          'optional': True,
                                                          'type': 'uint32'}],
                                          'version': 1}],
                             'name': 'ISteamWebUserPresenceOAuth'},
                            {'methods': [{'httpmethod': 'GET',
                                          'name': 'GetWorldStatus',
                                          'parameters': [],
                                          'version': 1}],
                             'name': 'ITFSystem_440'},
                            {'methods': [{'description': 'Tracks playtime for '
                                                         'a user when they are '
                                                         'offline',
                                          'httpmethod': 'POST',
                                          'name': 'RecordOfflinePlaytime',
                                          'parameters': [{'name': 'steamid',
                                                          'optional': False,
                                                          'type': 'uint64'},
                                                         {'name': 'ticket',
                                                          'optional': False,
                                                          'type': 'string'},
                                                         {'name': 'play_sessions',
                                                          'optional': False,
                                                          'type': '{message}'}],
                                          'version': 1}],
                             'name': 'IPlayerService'},
                            {'methods': [{'description': 'Creates an async '
                                                         'game session',
                                          'httpmethod': 'POST',
                                          'name': 'UserCreateSession',
                                          'parameters': [{'description': 'The '
                                                                         'appid '
                                                                         'to '
                                                                         'create '
                                                                         'the '
                                                                         'session '
                                                                         'for.',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': 'Game-specified '
                                                                         'context '
                                                                         'value '
                                                                         'the '
                                                                         'game '
                                                                         'can '
                                                                         'used '
                                                                         'to '
                                                                         'associate '
                                                                         'the '
                                                                         'session '
                                                                         'with '
                                                                         'some '
                                                                         'object '
                                                                         'on '
                                                                         'their '
                                                                         'backend.',
                                                          'name': 'context',
                                                          'optional': False,
                                                          'type': 'uint64'},
                                                         {'description': 'The '
                                                                         'title '
                                                                         'of '
                                                                         'the '
                                                                         'session '
                                                                         'to '
                                                                         'be '
                                                                         'displayed '
                                                                         'within '
                                                                         'each '
                                                                         "user's "
                                                                         'list '
                                                                         'of '
                                                                         'sessions.',
                                                          'name': 'title',
                                                          'optional': False,
                                                          'type': '{message}'},
                                                         {'description': 'The '
                                                                         'initial '
                                                                         'state '
                                                                         'of '
                                                                         'all '
                                                                         'users '
                                                                         'in '
                                                                         'the '
                                                                         'session.',
                                                          'name': 'users',
                                                          'optional': False,
                                                          'type': '{message}'},
                                                         {'description': '(Optional) '
                                                                         'steamid '
                                                                         'to '
                                                                         'make '
                                                                         'the '
                                                                         'request '
                                                                         'on '
                                                                         'behalf '
                                                                         'of '
                                                                         '-- '
                                                                         'if '
                                                                         'specified, '
                                                                         'the '
                                                                         'user '
                                                                         'must '
                                                                         'be '
                                                                         'in '
                                                                         'the '
                                                                         'session '
                                                                         'and '
                                                                         'all '
                                                                         'users '
                                                                         'being '
                                                                         'added '
                                                                         'to '
                                                                         'the '
                                                                         'session '
                                                                         'must '
                                                                         'be '
                                                                         'friends '
                                                                         'with '
                                                                         'the '
                                                                         'user.',
                                                          'name': 'steamid',
                                                          'optional': False,
                                                          'type': 'uint64'}],
                                          'version': 1},
                                         {'description': 'Updates an async '
                                                         'game session',
                                          'httpmethod': 'POST',
                                          'name': 'UserUpdateSession',
                                          'parameters': [{'description': 'The '
                                                                         'sessionid '
                                                                         'to '
                                                                         'update.',
                                                          'name': 'sessionid',
                                                          'optional': False,
                                                          'type': 'uint64'},
                                                         {'description': 'The '
                                                                         'appid '
                                                                         'of '
                                                                         'the '
                                                                         'session '
                                                                         'to '
                                                                         'update.',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': '(Optional) '
                                                                         'The '
                                                                         'new '
                                                                         'title '
                                                                         'of '
                                                                         'the '
                                                                         'session.  '
                                                                         'If '
                                                                         'not '
                                                                         'specified, '
                                                                         'the '
                                                                         'title '
                                                                         'will '
                                                                         'not '
                                                                         'be '
                                                                         'changed.',
                                                          'name': 'title',
                                                          'optional': False,
                                                          'type': '{message}'},
                                                         {'description': '(Optional) '
                                                                         'A '
                                                                         'list '
                                                                         'of '
                                                                         'users '
                                                                         'whose '
                                                                         'state '
                                                                         'will '
                                                                         'be '
                                                                         'updated '
                                                                         'to '
                                                                         'reflect '
                                                                         'the '
                                                                         'given '
                                                                         'state. '
                                                                         'If '
                                                                         'the '
                                                                         'users '
                                                                         'are '
                                                                         'not '
                                                                         'already '
                                                                         'in '
                                                                         'the '
                                                                         'session, '
                                                                         'they '
                                                                         'will '
                                                                         'be '
                                                                         'added '
                                                                         'to '
                                                                         'it.',
                                                          'name': 'users',
                                                          'optional': False,
                                                          'type': '{message}'},
                                                         {'description': '(Optional) '
                                                                         'steamid '
                                                                         'to '
                                                                         'make '
                                                                         'the '
                                                                         'request '
                                                                         'on '
                                                                         'behalf '
                                                                         'of '
                                                                         '-- '
                                                                         'if '
                                                                         'specified, '
                                                                         'the '
                                                                         'user '
                                                                         'must '
                                                                         'be '
                                                                         'in '
                                                                         'the '
                                                                         'session '
                                                                         'and '
                                                                         'all '
                                                                         'users '
                                                                         'being '
                                                                         'added '
                                                                         'to '
                                                                         'the '
                                                                         'session '
                                                                         'must '
                                                                         'be '
                                                                         'friends '
                                                                         'with '
                                                                         'the '
                                                                         'user.',
                                                          'name': 'steamid',
                                                          'optional': False,
                                                          'type': 'uint64'}],
                                          'version': 1},
                                         {'description': 'Deletes an async '
                                                         'game session',
                                          'httpmethod': 'POST',
                                          'name': 'UserDeleteSession',
                                          'parameters': [{'description': 'The '
                                                                         'sessionid '
                                                                         'to '
                                                                         'delete.',
                                                          'name': 'sessionid',
                                                          'optional': False,
                                                          'type': 'uint64'},
                                                         {'description': 'The '
                                                                         'appid '
                                                                         'of '
                                                                         'the '
                                                                         'session '
                                                                         'to '
                                                                         'delete.',
                                                          'name': 'appid',
                                                          'optional': False,
                                                          'type': 'uint32'},
                                                         {'description': '(Optional) '
                                                                         'steamid '
                                                                         'to '
                                                                         'make '
                                                                         'the '
                                                                         'request '
                                                                         'on '
                                                                         'behalf '
                                                                         'of '
                                                                         '-- '
                                                                         'if '
                                                                         'specified, '
                                                                         'the '
                                                                         'user '
                                                                         'must '
                                                                         'be '
                                                                         'in '
                                                                         'the '
                                                                         'session.',
                                                          'name': 'steamid',
                                                          'optional': False,
                                                          'type': 'uint64'}],
                                          'version': 1}],
                             'name': 'IGameNotificationsService'}]}}
